# This file serves as the template for generating database migration scripts.
"""fix workspace members

Revision ID: 408f4d768476
Revises: 5dea7797a75e
Create Date: 2026-06-07 18:50:01.326726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408f4d768476'
down_revision: Union[str, None] = '5dea7797a75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
