# This file serves as the template for generating database migration scripts.
"""add created_at to workspace_members

Revision ID: 5dea7797a75e
Revises: d0f9460db6e6
Create Date: 2026-06-07 18:10:20.325803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dea7797a75e'
down_revision: Union[str, None] = 'd0f9460db6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_members', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'created_at')
    # ### end Alembic commands ###
