# This file serves as the template for generating database migration scripts.
"""initial schema

Revision ID: d0f9460db6e6
Revises: feb7926d0542
Create Date: 2026-06-06 20:58:23.181745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f9460db6e6'
down_revision: Union[str, None] = 'feb7926d0542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
